export const SET_CONTACTS = 'SET_CONTACTS'
export const ADD_CONTACT = 'ADD_CONTACT'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export const SET_FAVORITE_CONTACTS = 'SET_FAVORITE_CONTACTS'
export const ADD_FAVORITE_CONTACT = 'ADD_FAVORITE_CONTACT'
export const REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT'

export const SET_GROUP_CONTACTS = 'SET_GROUP_CONTACTS'
export const ADD_GROUP_CONTACT = 'ADD_GROUP_CONTACT'
export const UPDATE_GROUP_CONTACT = 'UPDATE_GROUP_CONTACT'
export const DELETE_GROUP_CONTACT = 'DELETE_GROUP_CONTACT'
