export const SET_GROUP_CONTACTS = 'SET_GROUP_CONTACTS'
export const ADD_GROUP_CONTACT = 'ADD_GROUP_CONTACT'
export const UPDATE_GROUP_CONTACT = 'UPDATE_GROUP_CONTACT'
export const DELETE_GROUP_CONTACT = 'DELETE_GROUP_CONTACT'
